extends:
  - "@commitlint/config-conventional"

rules:
  subject-case: [2, "always", ["sentence-case"]]
  footer-max-line-length: [0, "always", 100]
  footer-max-length: [0, "always", 100]
  header-max-length: [0, "always", 100]
